import { DeveloperProfile, TokenLaunch } from '@/types';

export const COLORS = {
  primary: '#FBF0DF',
  text: '#3B3B3B',
  accent: '#FF7B7B',
  border: '#3B3B3B',
};

export const MOCK_LAUNCHES: TokenLaunch[] = [
  {
    id: 'fartcoin',
    name: 'Fartcoin',
    ticker: 'FARTCOIN',
    launchDate: '2024-10-15',
    score: 150,
    volume: '$1.2B',
    status: 'active',
  },
  {
    id: '1',
    name: 'Nebula Protocol',
    ticker: 'NEB',
    launchDate: '2023-11-12',
    score: 145,
    volume: '$12.5M',
    status: 'active',
  },
  {
    id: '2',
    name: 'DogeAI',
    ticker: 'DAI',
    launchDate: '2023-08-01',
    score: 45,
    volume: '$200K',
    status: 'inactive',
  },
  {
    id: '3',
    name: 'YieldFarming X',
    ticker: 'YFX',
    launchDate: '2024-01-15',
    score: 120,
    volume: '$4.2M',
    status: 'active',
  },
];

export const MOCK_DEVS: DeveloperProfile[] = [
  {
    id: 'fartcoin-dev',
    handle: 'HyYN...nMFF',
    displayName: 'Fartcoin Dev',
    avatarUrl: 'https://picsum.photos/200/200?random=fart',
    isVerified: true,
    totalScore: 738,
    rank: 1,
    walletAddress: 'HyYNVYmnFmi87NsQqWzLJhUTPBKQUfgfhdbBa554nMFF',
    joinedDate: '2024-10-15',
    launches: [MOCK_LAUNCHES[0]],
    tags: ['Meme', 'Legend', '$1B+'],
  },
  {
    id: 'dev1',
    handle: '@0xSatoshi_N',
    displayName: 'Satoshi Nakamoto (Sim)',
    avatarUrl: 'https://picsum.photos/200/200?random=1',
    isVerified: true,
    totalScore: 720,
    rank: 2,
    walletAddress: '0x123...abc',
    joinedDate: '2022-05-20',
    launches: [MOCK_LAUNCHES[1], MOCK_LAUNCHES[3]],
    tags: ['DeFi', 'L1', 'Legend'],
  },
  {
    id: 'dev2',
    handle: '@vitalik_b',
    displayName: 'Vitalik B',
    avatarUrl: 'https://picsum.photos/200/200?random=2',
    isVerified: true,
    totalScore: 680,
    rank: 3,
    walletAddress: '0x456...def',
    joinedDate: '2022-06-15',
    launches: [MOCK_LAUNCHES[3]],
    tags: ['Eth', 'Scaling'],
  },
  {
    id: 'dev3',
    handle: '0x789...123',
    displayName: 'Anon Dev',
    avatarUrl: 'https://picsum.photos/200/200?random=3',
    isVerified: false,
    totalScore: 450,
    rank: 4,
    walletAddress: '0x789...123',
    joinedDate: '2023-01-10',
    launches: [MOCK_LAUNCHES[2]],
    tags: ['Meme', 'High Risk'],
  },
  {
    id: 'dev4',
    handle: '@builder_bob',
    displayName: 'Builder Bob',
    avatarUrl: 'https://picsum.photos/200/200?random=4',
    isVerified: true,
    totalScore: 320,
    rank: 5,
    walletAddress: '0xabc...789',
    joinedDate: '2023-09-01',
    launches: [],
    tags: ['Infra'],
  },
  {
    id: 'dev5',
    handle: '0xdef...456',
    displayName: 'Rug Puller',
    avatarUrl: 'https://picsum.photos/200/200?random=5',
    isVerified: false,
    totalScore: 10,
    rank: 999,
    walletAddress: '0xdef...456',
    joinedDate: '2023-12-25',
    launches: [],
    tags: ['Scam'],
  },
];
